### ISSUE TITLE
How to run on custom input point cloud?

### ISSUE THREAD

**Issue by rakhimovv** [Xrvitd/RFEPS#4]
Hello! Thanks for your work!

Though I have not yet succeeded with installation, could you please provide instructions how to run it on custom point cloud, and in what format it must be in, number of points, range, etc

**Comment by Xrvitd** [comment]
Please use point clouds in xyz format with normals. It is a text file with six numbers in each line (x, y, z, nx, ny, nz). The position of the point cloud should be scaled to [0,1]^3. The optimal number of point clouds is around 50k. There are some inputs and results run by me in the '[ModelAndResultsInPaper]' folder. 
Finally, if you still can't install successfully, maybe send me the models you want to test (if not so many). My email is xrvitd@163.com. 
By the way, "DEF" is a great paper, we just discussed and studied it in our group meeting :)

**Comment by rakhimovv** [comment]
Great, thank you for the instructions!
