### ISSUE TITLE
Question about the settings of error measurement parameters

### ISSUE THREAD

**Issue by YuanYe-99** [Xrvitd/RFEPS#5]
Thanks for your wonderful work! Could you share your error measurement parameters, such as sample_num, f1_threshold, ef1_radius, ef1_dotproduct_threshold and ef1_threshold? I tried to use the code of error measurement provided by NMC that you maybe know. The result‘s order of magnitude is different. Hope you can help me to solve this problem.

**Comment by YuanYe-99** [comment]
> @YuanYe-99
> 
> Hi,
> 
> Thank you for your support and attention to our work.
> 
> We first normlize the shape to [-0.5, 0.5] and then sample 100000 points for each shape. The threshold are shown below (If I'm not mistaken, the ef1 threshold is same as NMC but with different bbox or sample num):
> 
> * sample_num = 100000
> * f1_threshold = 0.003
> * ef1_radius = 0.004
> * ef1_dotproduct_threshold = 0.2
> * ef1_threshold = 0.005

Thanks for your reply! What's your method to normalize the shape?  I have tried my way to normalize the shape but the order of magnitude maybe still not same.

**Comment by bearprin** [comment]
Well, here are our eval code @YuanYe-99 

```python
import os

import trimesh
import numpy as np
from scipy.spatial import KDTree
import tqdm

sample_num = 100000
f1_threshold = 0.003
ef1_radius = 0.004
ef1_dotproduct_threshold = 0.2
ef1_threshold = 0.005


def normalize_mesh_export(mesh, file_out=None):
    bounds = mesh.extents
    if bounds.min() == 0.0:
        return

    # translate to origin
    translation = (mesh.bounds[0] + mesh.bounds[1]) * 0.5
    translation = trimesh.transformations.translation_matrix(direction=-translation)
    mesh.apply_transform(translation)

    # scale to unit cube
    scale = 1.0 / bounds.max()
    scale_trafo = trimesh.transformations.scale_matrix(factor=scale)
    mesh.apply_transform(scale_trafo)
    if file_out is not None:
        mesh.export(file_out)
    return mesh


def eval_reconstruct_gt_mesh(pred_mesh: trimesh.Trimesh, gt_mesh: trimesh.Trimesh, sample_num=100000):
    gt_mesh = normalize_mesh_export(gt_mesh)
    pred_mesh = normalize_mesh_export(pred_mesh)

    # load gt
    gt_points, gt_indexs = gt_mesh.sample(sample_num, return_index=True)
    gt_normals = gt_mesh.face_normals[gt_indexs]
    # load pred
    pred_points, pred_indexs = pred_mesh.sample(sample_num, return_index=True)
    pred_normals = pred_mesh.face_normals[pred_indexs]

    # cd and nc and f1
    # from gt to pred
    pred_tree = KDTree(pred_points)
    dist, inds = pred_tree.query(gt_points, k=1, workers=-1)
    recall = np.sum(dist < f1_threshold) / float(len(dist))
    dist = np.square(dist)
    gt2pred_mean_cd = np.mean(dist)
    neighbor_normals = pred_normals[np.squeeze(inds)]
    dotproduct = np.abs(np.sum(gt_normals * neighbor_normals, axis=1))
    gt2pred_nc = np.mean(dotproduct)

    # from pred to gt
    gt_tree = KDTree(gt_points)
    dist, inds = gt_tree.query(pred_points, k=1, workers=-1)
    precision = np.sum(dist < f1_threshold) / float(len(dist))
    dist = np.square(dist)
    pred2gt_mean_cd = np.mean(dist)
    neighbor_normals = gt_normals[np.squeeze(inds)]
    dotproduct = np.abs(np.sum(pred_normals * neighbor_normals, axis=1))
    pred2gt_nc = np.mean(dotproduct)

    cd = gt2pred_mean_cd + pred2gt_mean_cd
    nc = (gt2pred_nc + pred2gt_nc) / 2
    if recall + precision > 0:
        f1 = 2 * recall * precision / (recall + precision)
    else:
        f1 = 0

    # sample gt edge points
    indslist = gt_tree.query_ball_point(gt_points, ef1_radius, workers=-1)
    flags = np.zeros([len(gt_points)], np.bool)
    for p in range(len(gt_points)):
        inds = indslist[p]
        if len(inds) > 0:
            this_normals = gt_normals[p:p + 1]
            neighbor_normals = gt_normals[inds]
            dotproduct = np.abs(np.sum(this_normals * neighbor_normals, axis=1))
            if np.any(dotproduct < ef1_dotproduct_threshold):
                flags[p] = True
    gt_edge_points = np.ascontiguousarray(gt_points[flags])

    # sample pred edge points
    indslist = pred_tree.query_ball_point(pred_points, ef1_radius, workers=-1)
    flags = np.zeros([len(pred_points)], np.bool)
    for p in range(len(pred_points)):
        inds = indslist[p]
        if len(inds) > 0:
            this_normals = pred_normals[p:p + 1]
            neighbor_normals = pred_normals[inds]
            dotproduct = np.sum(this_normals * neighbor_normals, axis=1)
            if np.any(dotproduct < ef1_dotproduct_threshold):
                flags[p] = True
    pred_edge_points = np.ascontiguousarray(pred_points[flags])

    # ecd ef1
    if len(pred_edge_points) == 0: pred_edge_points = np.zeros([486, 3], np.float32)
    if len(gt_edge_points) == 0:
        ecd = 0
        ef1 = 1
    else:
        # from gt to pred
        tree = KDTree(pred_edge_points)
        dist, inds = tree.query(gt_edge_points, k=1)
        recall = np.sum(dist < ef1_threshold) / float(len(dist))
        dist = np.square(dist)
        gt2pred_mean_ecd = np.mean(dist)

        # from pred to gt
        tree = KDTree(gt_edge_points)
        dist, inds = tree.query(pred_edge_points, k=1)
        precision = np.sum(dist < ef1_threshold) / float(len(dist))
        dist = np.square(dist)
        pred2gt_mean_ecd = np.mean(dist)

        ecd = gt2pred_mean_ecd + pred2gt_mean_ecd
        if recall + precision > 0:
            ef1 = 2 * recall * precision / (recall + precision)
        else:
            ef1 = 0

    return cd, nc, f1, ecd, ef1


def eval_dataset(rec_dataset_path, gt_mesh_path):
    files = [f for f in filter(lambda x: 'trimesh' in x, sorted(os.listdir(rec_dataset_path)))]
    csv_lines = [
        'files, cd(x10^2), normals_correctness, f1, ecd(x10^2), ef1']
    csv_lines = ''.join(csv_lines)
    with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'w') as text_file:
        text_file.write(csv_lines)

    cd_list = []
    nc = []
    f1_list = []
    ecd_list = []
    ef1_list = []
    for f in tqdm.tqdm(files):
        lines = list()
        if os.path.splitext(f)[1] not in ['.obj', '.ply', '.off']:
            continue
        name = os.path.splitext(f)[0]
        try:
            rec_mesh = normalize_mesh_export(
                trimesh.load(os.path.join(rec_dataset_path, f), process=True))
        except ValueError:
            print('{} does not exist'.format(os.path.join(rec_dataset_path, f)))
            continue

        try:
            gt_mesh = normalize_mesh_export(trimesh.load(os.path.join(gt_mesh_path, name + '.obj'), process=False))
        except ValueError:
            print('{} does not exist'.format(os.path.join(gt_mesh_path, name + '.obj')))
            continue

        cd, normals_correctness, f1, ecd, ef1 = eval_reconstruct_gt_mesh(rec_mesh, gt_mesh)

        cd *= 100
        ecd *= 100

        cd_list.append(cd)
        nc.append(normals_correctness)
        f1_list.append(f1)
        ecd_list.append(ecd)
        ef1_list.append(ef1)
        print('files', f,
              #       'cd:', cd,
              #       'nc:', normals_correctness,
              #       'f1:', f1,
              #       'ecd:', ecd,
              #       'ef1:', ef1
              )
        lines.append('\n')
        lines.append(str(f))
        lines.append(',' + str(cd))
        lines.append(',' + str(normals_correctness))
        lines.append(',' + str(f1))
        lines.append(',' + str(ecd))
        lines.append(',' + str(ef1))
        lines = ''.join(lines)
        with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
            text_file.write(lines)

    lines = list()
    lines.append('\n')
    lines.append(str('sum'))
    lines.append(',' + str(np.sum(cd_list)))
    lines.append(',' + str(np.sum(nc)))
    lines.append(',' + str(np.sum(f1_list)))
    lines.append(',' + str(np.sum(ecd_list)))
    lines.append(',' + str(np.sum(ef1_list)))
    lines = ''.join(lines)
    with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
        text_file.write(lines)

    ##
    filter_num = 10
    cd_list = np.sort(np.array(cd_list))[:-filter_num]
    nc = np.sort(np.array(nc))[filter_num:]
    f1_list = np.sort(np.array(f1_list))[filter_num:]
    ecd_list = np.sort(np.array(ecd_list))[:-filter_num]
    ef1_list = np.sort(np.array(ef1_list))[filter_num:]

    lines = list()
    lines.append('\n')
    lines.append(str('mean/radio'))
    lines.append(',' + str(np.mean(cd_list)))
    lines.append(',' + str(np.mean(nc)))
    lines.append(',' + str(np.mean(f1_list)))
    lines.append(',' + str(np.mean(ecd_list)))
    lines.append(',' + str(np.mean(ef1_list)))
    lines = ''.join(lines)
    with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
        text_file.write(lines)
    print(
        'mean_cd', np.mean(cd_list),
        'mean_nc', np.mean(nc),
        'mean_f1', np.mean(f1_list),
        'mean_ecd', np.mean(ecd_list),
        'mean_ef1', np.mean(ef1_list),
    )


if __name__ == '__main__':
    dir_ = '/Users/bear/Dropbox/Research/Paper/SIG-2022-Feature-preserving-recon/experiment/Ours_Rec'
    f = [os.path.join(dir_, f) for f in
         filter(lambda x: x != '.DS_Store' and 'ours' in x, os.listdir(dir_))]
    for ff in tqdm.tqdm(f):
        print(ff)
        eval_dataset(
            ff,
            '/Users/bear/Dropbox/Research/Paper/SIG-2022-Feature-preserving-recon/data/abc_chunk4_mesh'
        )
```

**Comment by YuanYe-99** [comment]
> Well, here are our eval code @YuanYe-99
> 
> ```python
> import os
> 
> import trimesh
> import numpy as np
> from scipy.spatial import KDTree
> import tqdm
> 
> sample_num = 100000
> f1_threshold = 0.003
> ef1_radius = 0.004
> ef1_dotproduct_threshold = 0.2
> ef1_threshold = 0.005
> 
> 
> def normalize_mesh_export(mesh, file_out=None):
>     bounds = mesh.extents
>     if bounds.min() == 0.0:
>         return
> 
>     # translate to origin
>     translation = (mesh.bounds[0] + mesh.bounds[1]) * 0.5
>     translation = trimesh.transformations.translation_matrix(direction=-translation)
>     mesh.apply_transform(translation)
> 
>     # scale to unit cube
>     scale = 1.0 / bounds.max()
>     scale_trafo = trimesh.transformations.scale_matrix(factor=scale)
>     mesh.apply_transform(scale_trafo)
>     if file_out is not None:
>         mesh.export(file_out)
>     return mesh
> 
> 
> def eval_reconstruct_gt_mesh(pred_mesh: trimesh.Trimesh, gt_mesh: trimesh.Trimesh, sample_num=100000):
>     gt_mesh = normalize_mesh_export(gt_mesh)
>     pred_mesh = normalize_mesh_export(pred_mesh)
> 
>     # load gt
>     gt_points, gt_indexs = gt_mesh.sample(sample_num, return_index=True)
>     gt_normals = gt_mesh.face_normals[gt_indexs]
>     # load pred
>     pred_points, pred_indexs = pred_mesh.sample(sample_num, return_index=True)
>     pred_normals = pred_mesh.face_normals[pred_indexs]
> 
>     # cd and nc and f1
>     # from gt to pred
>     pred_tree = KDTree(pred_points)
>     dist, inds = pred_tree.query(gt_points, k=1, workers=-1)
>     recall = np.sum(dist < f1_threshold) / float(len(dist))
>     dist = np.square(dist)
>     gt2pred_mean_cd = np.mean(dist)
>     neighbor_normals = pred_normals[np.squeeze(inds)]
>     dotproduct = np.abs(np.sum(gt_normals * neighbor_normals, axis=1))
>     gt2pred_nc = np.mean(dotproduct)
> 
>     # from pred to gt
>     gt_tree = KDTree(gt_points)
>     dist, inds = gt_tree.query(pred_points, k=1, workers=-1)
>     precision = np.sum(dist < f1_threshold) / float(len(dist))
>     dist = np.square(dist)
>     pred2gt_mean_cd = np.mean(dist)
>     neighbor_normals = gt_normals[np.squeeze(inds)]
>     dotproduct = np.abs(np.sum(pred_normals * neighbor_normals, axis=1))
>     pred2gt_nc = np.mean(dotproduct)
> 
>     cd = gt2pred_mean_cd + pred2gt_mean_cd
>     nc = (gt2pred_nc + pred2gt_nc) / 2
>     if recall + precision > 0:
>         f1 = 2 * recall * precision / (recall + precision)
>     else:
>         f1 = 0
> 
>     # sample gt edge points
>     indslist = gt_tree.query_ball_point(gt_points, ef1_radius, workers=-1)
>     flags = np.zeros([len(gt_points)], np.bool)
>     for p in range(len(gt_points)):
>         inds = indslist[p]
>         if len(inds) > 0:
>             this_normals = gt_normals[p:p + 1]
>             neighbor_normals = gt_normals[inds]
>             dotproduct = np.abs(np.sum(this_normals * neighbor_normals, axis=1))
>             if np.any(dotproduct < ef1_dotproduct_threshold):
>                 flags[p] = True
>     gt_edge_points = np.ascontiguousarray(gt_points[flags])
> 
>     # sample pred edge points
>     indslist = pred_tree.query_ball_point(pred_points, ef1_radius, workers=-1)
>     flags = np.zeros([len(pred_points)], np.bool)
>     for p in range(len(pred_points)):
>         inds = indslist[p]
>         if len(inds) > 0:
>             this_normals = pred_normals[p:p + 1]
>             neighbor_normals = pred_normals[inds]
>             dotproduct = np.sum(this_normals * neighbor_normals, axis=1)
>             if np.any(dotproduct < ef1_dotproduct_threshold):
>                 flags[p] = True
>     pred_edge_points = np.ascontiguousarray(pred_points[flags])
> 
>     # ecd ef1
>     if len(pred_edge_points) == 0: pred_edge_points = np.zeros([486, 3], np.float32)
>     if len(gt_edge_points) == 0:
>         ecd = 0
>         ef1 = 1
>     else:
>         # from gt to pred
>         tree = KDTree(pred_edge_points)
>         dist, inds = tree.query(gt_edge_points, k=1)
>         recall = np.sum(dist < ef1_threshold) / float(len(dist))
>         dist = np.square(dist)
>         gt2pred_mean_ecd = np.mean(dist)
> 
>         # from pred to gt
>         tree = KDTree(gt_edge_points)
>         dist, inds = tree.query(pred_edge_points, k=1)
>         precision = np.sum(dist < ef1_threshold) / float(len(dist))
>         dist = np.square(dist)
>         pred2gt_mean_ecd = np.mean(dist)
> 
>         ecd = gt2pred_mean_ecd + pred2gt_mean_ecd
>         if recall + precision > 0:
>             ef1 = 2 * recall * precision / (recall + precision)
>         else:
>             ef1 = 0
> 
>     return cd, nc, f1, ecd, ef1
> 
> 
> def eval_dataset(rec_dataset_path, gt_mesh_path):
>     files = [f for f in filter(lambda x: 'trimesh' in x, sorted(os.listdir(rec_dataset_path)))]
>     csv_lines = [
>         'files, cd(x10^2), normals_correctness, f1, ecd(x10^2), ef1']
>     csv_lines = ''.join(csv_lines)
>     with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'w') as text_file:
>         text_file.write(csv_lines)
> 
>     cd_list = []
>     nc = []
>     f1_list = []
>     ecd_list = []
>     ef1_list = []
>     for f in tqdm.tqdm(files):
>         lines = list()
>         if os.path.splitext(f)[1] not in ['.obj', '.ply', '.off']:
>             continue
>         name = os.path.splitext(f)[0]
>         try:
>             rec_mesh = normalize_mesh_export(
>                 trimesh.load(os.path.join(rec_dataset_path, f), process=True))
>         except ValueError:
>             print('{} does not exist'.format(os.path.join(rec_dataset_path, f)))
>             continue
> 
>         try:
>             gt_mesh = normalize_mesh_export(trimesh.load(os.path.join(gt_mesh_path, name + '.obj'), process=False))
>         except ValueError:
>             print('{} does not exist'.format(os.path.join(gt_mesh_path, name + '.obj')))
>             continue
> 
>         cd, normals_correctness, f1, ecd, ef1 = eval_reconstruct_gt_mesh(rec_mesh, gt_mesh)
> 
>         cd *= 100
>         ecd *= 100
> 
>         cd_list.append(cd)
>         nc.append(normals_correctness)
>         f1_list.append(f1)
>         ecd_list.append(ecd)
>         ef1_list.append(ef1)
>         print('files', f,
>               #       'cd:', cd,
>               #       'nc:', normals_correctness,
>               #       'f1:', f1,
>               #       'ecd:', ecd,
>               #       'ef1:', ef1
>               )
>         lines.append('\n')
>         lines.append(str(f))
>         lines.append(',' + str(cd))
>         lines.append(',' + str(normals_correctness))
>         lines.append(',' + str(f1))
>         lines.append(',' + str(ecd))
>         lines.append(',' + str(ef1))
>         lines = ''.join(lines)
>         with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
>             text_file.write(lines)
> 
>     lines = list()
>     lines.append('\n')
>     lines.append(str('sum'))
>     lines.append(',' + str(np.sum(cd_list)))
>     lines.append(',' + str(np.sum(nc)))
>     lines.append(',' + str(np.sum(f1_list)))
>     lines.append(',' + str(np.sum(ecd_list)))
>     lines.append(',' + str(np.sum(ef1_list)))
>     lines = ''.join(lines)
>     with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
>         text_file.write(lines)
> 
>     ##
>     filter_num = 10
>     cd_list = np.sort(np.array(cd_list))[:-filter_num]
>     nc = np.sort(np.array(nc))[filter_num:]
>     f1_list = np.sort(np.array(f1_list))[filter_num:]
>     ecd_list = np.sort(np.array(ecd_list))[:-filter_num]
>     ef1_list = np.sort(np.array(ef1_list))[filter_num:]
> 
>     lines = list()
>     lines.append('\n')
>     lines.append(str('mean/radio'))
>     lines.append(',' + str(np.mean(cd_list)))
>     lines.append(',' + str(np.mean(nc)))
>     lines.append(',' + str(np.mean(f1_list)))
>     lines.append(',' + str(np.mean(ecd_list)))
>     lines.append(',' + str(np.mean(ef1_list)))
>     lines = ''.join(lines)
>     with open(os.path.join(rec_dataset_path, 'rec_compare_abc.csv'), 'a') as text_file:
>         text_file.write(lines)
>     print(
>         'mean_cd', np.mean(cd_list),
>         'mean_nc', np.mean(nc),
>         'mean_f1', np.mean(f1_list),
>         'mean_ecd', np.mean(ecd_list),
>         'mean_ef1', np.mean(ef1_list),
>     )
> 
> 
> if __name__ == '__main__':
>     dir_ = '/Users/bear/Dropbox/Research/Paper/SIG-2022-Feature-preserving-recon/experiment/Ours_Rec'
>     f = [os.path.join(dir_, f) for f in
>          filter(lambda x: x != '.DS_Store' and 'ours' in x, os.listdir(dir_))]
>     for ff in tqdm.tqdm(f):
>         print(ff)
>         eval_dataset(
>             ff,
>             '/Users/bear/Dropbox/Research/Paper/SIG-2022-Feature-preserving-recon/data/abc_chunk4_mesh'
>         )
> ```

I'm truly grateful for your help.
