### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by aiolosgs** [Xrvitd/RFEPS#6]
Hi，thanks for your great work！
I wonder is there any advice on how to improve the performance of your code.  I run the code with a point cloud of 20,000 points, and it costs about 20s. Is it possible to make the algorithm run faster?
Have you tried other optimization algorithms in alglib?

**Comment by Xrvitd** [comment]
Hello, thank you for your attention. At present, the performance of the algorithm is really poor. You can try to enable AVX2, openmp and use more core CPUs to speed up the code. And so far I have only tried another implementation of L-BFGS, but the effect is not as good as the current alglib implementation.
