### ISSUE TITLE
oom crash

### ISSUE THREAD

**Issue by zhouilu** [Xrvitd/RFEPS#7]
demo (input: 01_82-block.xyz) coast 70GB memory on mac,  is this correct?

**Comment by Xrvitd** [comment]
Maybe check the file name in your code？ It may cost large memory when you input a file which is not exist.

| |
Rui Xu
Shandong University
***@***.***
Qingdao, China
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 02/01/2024 17:00 |
| To | Xrvitd/RFEPS ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [Xrvitd/RFEPS] oom crash (Issue #7) |

demo (input: 01_82-block.xyz) coast 70GB memory on mac, is this correct?

**Comment by zhouilu** [comment]
thanks reply. It is caused by the difference between mac and windows input paths.
